name: Deploy to Aliyun

on:
  push:
    branches: [ main ]  # 根据你的主分支名称调整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd onething
        npm ci --legacy-peer-deps
        
    - name: Build project
      run: |
        cd onething
        CI=false npm run build
        
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v3
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary
        if_key_exists: replace
        
    - name: Adding Known Hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      
    - name: Deploy to Aliyun
      run: |
        # 设置SSH密钥权限
        chmod 600 ~/.ssh/id_rsa*
        
        # 创建部署目录
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /var/www/onething"
        
        # 压缩构建文件，提高传输效率
        cd onething
        tar -czf build.tar.gz build server.js package.json package-lock.json .env.example
        
        # 传输文件到服务器
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/onething/
        
        # 在服务器上解压并安装依赖，配置MongoDB
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/onething && \
          tar -xzf build.tar.gz && \
          rm build.tar.gz && \
          npm install --production --legacy-peer-deps && \
          cp .env.example .env && \
          sed -i 's/MONGO_URL=.*/MONGO_URL=${{ secrets.MONGO_URL }}/' .env && \
          sed -i 's/MONGO_DB_NAME=.*/MONGO_DB_NAME=${{ secrets.MONGO_DB }}/' .env && \
          sed -i 's/MONGO_PASSWORD=.*/MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}/' .env && \
          sed -i 's/MONGO_USER=.*/MONGO_USER=${{ secrets.MONGO_USER }}/' .env && \
          pm2 restart onething || pm2 start server.js --name onething"