name: Deploy to Aliyun

on:
  push:
    branches: [ main ]  # 根据你的主分支名称调整

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'onething/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd onething
        echo "Cleaning previous node_modules and package-lock..."
        rm -rf node_modules package-lock.json # 强制清理
        npm ci --legacy-peer-deps
        
    - name: Build project
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || '' }}
      run: |
        cd onething
        echo "Cleaning previous build directory..."
        rm -rf build # 强制清理旧构建
        CI=false npm run build
        
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Adding Known Hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      
    - name: Deploy to Aliyun
      run: |
        # 创建部署目录
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "mkdir -p /var/www/onething"
        
        # 压缩构建文件，提高传输效率
        cd onething
        tar -czf build.tar.gz build server.js package.json package-lock.json .env.example schema/ ecosystem.config.js
        
        # 传输文件到服务器
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/onething/
        
        # 在服务器上解压并安装依赖，配置MongoDB和环境变量
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/onething && \
          tar -xzf build.tar.gz && \
          rm build.tar.gz && \
          npm install --production --legacy-peer-deps && \
          cp .env.example .env && \
          sed -i 's/MONGO_URL=.*/MONGO_URL=${{ secrets.MONGO_URL }}/' .env && \
          sed -i 's/MONGO_DB_NAME=.*/MONGO_DB_NAME=${{ secrets.MONGO_DB }}/' .env && \
          sed -i 's/MONGO_PASSWORD=.*/MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}/' .env && \
          sed -i 's/MONGO_USER=.*/MONGO_USER=${{ secrets.MONGO_USER }}/' .env && \
          sed -i "s/PORT=.*/PORT=${{ secrets.PORT || '5005' }}/" .env && \
          sed -i "s/^NODE_ENV=.*$/NODE_ENV=production/" .env && \
          if grep -q \"^DEEPSEEK_API_KEY=\" .env; then sed -i \"s/^DEEPSEEK_API_KEY=.*$/DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}/\" .env; else echo \"DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}\" >> .env; fi && \
          if grep -q \"^BACKUP_AI_API_URL=\" .env; then sed -i \"s|^BACKUP_AI_API_URL=.*$|BACKUP_AI_API_URL=${{ secrets.BACKUP_AI_API_URL }}|\" .env; else echo \"BACKUP_AI_API_URL=${{ secrets.BACKUP_AI_API_URL }}\" >> .env; fi && \
          if grep -q \"^BACKUP_AI_API_KEY=\" .env; then sed -i \"s/^BACKUP_AI_API_KEY=.*$/BACKUP_AI_API_KEY=${{ secrets.BACKUP_AI_API_KEY }}/\" .env; else echo \"BACKUP_AI_API_KEY=${{ secrets.BACKUP_AI_API_KEY }}\" >> .env; fi && \
          cp ecosystem.config.js . && \
          pm2 delete onething || true && \
          pm2 start ecosystem.config.js --env production && \
          pm2 save"
        
        echo "部署完成! 请确保Nginx正确配置了后端端口 (${{ secrets.PORT || '5005' }}) 的代理"